import { write } from "./index";
import { GenerationOptions } from "./prompt";

export async function genGraphic(bundleName: string, bundlePath: string): Promise<void> {
    const graphic = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
        }
    </style>
</head>
<body>
    <!-- You can display anything you want here and add it to your broadcater software by adding a webview with
     a link to this graphic. -->
    <p>
        Hello, I'm the graphic of bundle "${bundleName}" that was generated by nodecg-io-cli.
    </p>

    <script>
        // You can use the nodecg object here to e.g. send and receive nodecg messages or access replicants.
        nodecg.log.info("Hello World, I'm bundle ${bundleName}.");
    </script>
</body>
</html>
`;

    await write(graphic, bundlePath, "graphics", "index.html");
}

export function genNodeCGGraphicConfig(
    opts: GenerationOptions,
): { file: string; width: number; height: number }[] | undefined {
    if (!opts.genGraphic) {
        return undefined;
    }

    return [
        {
            file: "index.html",
            width: 1920,
            height: 1080,
        },
    ];
}
