name: Linter

on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with: 
        node-version: 16

    - name: Install dependencies
      run: npm i

    - name: Run ESLint
      run: npm run lint